# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

time_series_operations <- function(ts_list, op, alpha) {
    .Call(`_HCVisR_time_series_operations`, ts_list, op, alpha)
}

